### ISSUE TITLE
Conflict: Constraint vulcan:lib errors

### ISSUE THREAD

**Issue by veerjainATgmail** [SachaG/SidebarVulcan#1]
HI,

I am running the latest SidebarVulcan with Vulcan - devel branch.
Getting the following error with the usage
METEOR_PACKAGE_DIRS="~/Vulcan/packages" meteor --port 3000 --settings settings.json

How to interpret the following error and fix the dependencies? Any help?

Thanks,
veerjain.

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint vulcan:lib@=1.16.0 is not satisfied by vulcan:lib 1.3.2.
   Constraints on package "vulcan:lib":
   * vulcan:lib@=1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:users 1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:i18n 1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@1.10.1 <- vulcan:ui-bootstrap 1.10.1 <- sidebar2020 0.0.0
   
   Conflict: Constraint email@1.0.4 is not satisfied by email 2.0.0.
   Constraints on package "email":
   * email@~2.0.0 <- top level
   * email@1.0.4 <- vulcan:lib 1.3.2 <- vulcan:core 1.16.0
   * email@1.0.10 <- vulcan:accounts 1.3.2 <- sidebar2020 0.0.0
   
   Conflict: Constraint vulcan:lib@1.10.1 is not satisfied by vulcan:lib 1.3.2.
   Constraints on package "vulcan:lib":
   * vulcan:lib@=1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:users 1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:i18n 1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@1.10.1 <- vulcan:ui-bootstrap 1.10.1 <- sidebar2020 0.0.0
   
   Conflict: Constraint email@1.0.10 is not satisfied by email 2.0.0.
   Constraints on package "email":
   * email@~2.0.0 <- top level
   * email@1.0.4 <- vulcan:lib 1.3.2 <- vulcan:core 1.16.0
   * email@1.0.10 <- vulcan:accounts 1.3.2 <- sidebar2020 0.0.0
   
=> Your application has errors. Waiting for file change.

**Comment by SachaG** [comment]
Meteor's package system is not great at resolving version conflicts. This basically means you need to get all instances of the `vulcan:lib` package to the same version (1.16.0). The best way to do that is to hardcode the version numbers either in:

1. Your `.meteor/packages` file  (you can remove the packages from there once they load properly)
2. Your app (in this case the `sidebar2020` package)'s `package.js` file

Sometimes deleting your `.meteor/versions` file also helps reset everything to the right version. Hope that helps!

**Comment by SachaG** [comment]
Actually I just pushed a commit that hardcodes package versions in `package.js`, maybe try with that first.

**Comment by veerjainATgmail** [comment]
@SachaG , Thanks for the response.

I did 1) .meteor/packages file version number hardcode as below
vulcan:core@1.16.0

vulcan:i18n-en-us@1.16.0

accounts-twitter@1.4.2
vulcan:newsletter@1.16.0

sidebar2020

>>>> I still see the same errors.

2) took the latest sidebar
So, SidebarVulcan/packages/packages/sidebar2020/packages.json has the following
Package.describe({
  name: `sidebar2020`,
});

const version = `1.16.0`;
....

it didnt solve it. So, still trying to figure out.

https://docs.vulcanjs.org/#Two-Repo-Install-Optional specify the usage as 
running like, 
METEOR_PACKAGE_DIRS="/Users/sacha/Vulcan/packages" meteor --port 3000 --settings settings.json
with specified Vulcan package directory. 
https://github.com/SachaG/SidebarVulcan/ usage is just 'yarn start'
wondering, if both results are same?

Also, there is no .metor/version file under SidebarVulcan folder or ~/.meteor folder

**Comment by SachaG** [comment]
`yarn start` will run the start script in `package.json` which is `ROOT_URL=http://localhost:5000 meteor --settings settings.json --port 5000`.

So no it's not the same, `yarn start` will only use your local packages if you've configured your path. 

But anyway an easy way to check if the 2-repo install is successful is to modify any file in the main Vulcan repo and see if that triggers a rebuild while your app is running. 

> Also, there is no .metor/version file under SidebarVulcan folder or ~/.meteor folder

Maybe it's not being created because the app is not launching? You could always try to disable the `sidebar2020` package in `.meteor/packages` and see if the app runs at least?

**Comment by veerjainATgmail** [comment]
Thanks. Thats a good suggestion. 

Few updates (documenting here for the benifit of others like me :smile:)

1) i removed .meteor/packages line "sidebar2020". Few notes.
       1a) with local Vulcan - devel branch , i.e, specifying the meteor package METEOR_PACKAGE_DIRS=<dir>/Vulcan/packages.. get unknown type - NewsletterFilterInput
       1b) with meteor package Vulcan (~/.meteor/packages) version ie. without specifying the METEOR_PACKAGE_DIRS get
   Constraints on package "email" error.

Thanks,
veerjain

Logs 1)
________________________________________________________________________________________________
diff --git a/.meteor/packages b/.meteor/packages
index 2c438d1..05edc7c 100644
--- a/.meteor/packages
+++ b/.meteor/packages
@@ -5,4 +5,3 @@ vulcan:i18n-en-us
 accounts-twitter@1.4.2
 vulcan:newsletter
 
-sidebar2020
Log 1a)
________________________________________________________________________________________
W20200829-10:06:30.787(5.5)? (STDERR) Error: Unknown type "NewsletterFilterInput". Did you mean "NewsletterSelectorInput", "UserFilterInput", "DeleteUserInput", "NewsletterMutationOutput", or "DeleteNewsletterInput"?
W20200829-10:06:30.788(5.5)? (STDERR) 
W20200829-10:06:30.788(5.5)? (STDERR) Unknown type "NewsletterFilterInput". Did you mean "NewsletterSelectorInput", "UserFilterInput", "DeleteUserInput", "NewsletterMutationOutput", or "DeleteNewsletterInput"?
W20200829-10:06:30.789(5.5)? (STDERR) 
W20200829-10:06:30.789(5.5)? (STDERR) Unknown type "NewsletterSortInput". Did you mean "NewsletterSelectorInput", "DeleteUserInput", "UserSortInput", "ResetPasswordInput", or "NewsletterMutationOutput"?
W20200829-10:06:30.789(5.5)? (STDERR) 
W20200829-10:06:30.790(5.5)? (STDERR) Unknown type "NewsletterFilterInput". Did you mean "NewsletterSelectorInput", "UserFilterInput", "DeleteUserInput", "NewsletterMutationOutput", or "DeleteNewsletterInput"?
W20200829-10:06:30.790(5.5)? (STDERR) 
W20200829-10:06:30.790(5.5)? (STDERR) Unknown type "NewsletterSortInput". Did you mean "NewsletterSelectorInput", "DeleteUserInput", "UserSortInput", "ResetPasswordInput", or "NewsletterMutationOutput"

______
Log 1b)
_____________________________________________________________________________________________
 ROOT_URL=http://localhost:5000 meteor --settings settings.json --port 5000
[[[[[ ~/workspace/Aug25/vulcan/SidebarVulcan ]]]]]

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint email@1.0.4 is not satisfied by email
   2.0.0.
   Constraints on package "email":
   * email@~2.0.0 <- top level
   * email@1.0.4 <- vulcan:lib 1.4.0 <- vulcan:core 1.4.0
   
=> Your application has errors. Waiting for file change.

In both experiments, deleted ./meteor/local

**Comment by veerjainATgmail** [comment]
Closing this issue.. 
Im assuming error are related meteor packaging logic and its dependency logic. , may not be related to Sidebar :+1:
